import type { Metadata } from "next";
import { store } from "./store/store";
import { Provider } from "react-redux";
import "./globals.css";
import Header from "./components/Header";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="bg-gray-100" suppressHydrationWarning={true}>
        <div className="p-12">
          <Provider store={store}>
            <div className="p-12">
              <Header />
              {children}
            </div>
          </Provider>
        </div>
      </body>
    </html>
  );
}
